@hostname = localhost
@port = 5001
@host = {{hostname}}:{{port}}

POST http://{{host}}/api/login/password
Content-Type: application/x-www-form-urlencoded

username=admin@admin.com&password=secret
###
GET http://{{host}}/api/users/
###
POST http://{{host}}/api/articles
Content-Type: application/json

{ 
    "title":"test title entertainment",
    "tags": ["Entertainment"],
    "content": "Test content",
    "weight": 1,
    "imageURL": "test",
    "author": "test"
}
###
POST http://{{host}}/api/articles
Content-Type: application/json

{ 
    "title":"test title politics",
    "tags": ["Politics"],
    "content": "Test content",
    "weight": 2,
    "imageURL": "test",
    "author": "test"
}
###
POST http://{{host}}/api/articles
Content-Type: application/json

{ 
    "title":"test title sports",
    "tags": ["Sports"],
    "content": "Test content",
    "weight": 3,
    "imageURL": "test",
    "author": "test"
}
###
POST http://{{host}}/api/login/logout
###
POST http://{{host}}/api/users/
Content-Type: application/json

{
    "email": "test@test.com",
    "role": "regular",
    "interests": ["Politics"],
    "password": "secret"
}
###
POST http://{{host}}/api/login/password
Content-Type: application/x-www-form-urlencoded

username=test@test.com&password=secret
###
GET http://{{host}}/api/users/
###
GET http://{{host}}/api/feed
###
GET http://{{host}}/api/articles/6388c37af7a43959c2538dd4
###
GET http://{{host}}/api/articles?sort=requests
###
GET http://{{host}}/api/articles?sort=weight
